### ISSUE TITLE
为什么考研狗勿扰？

### ISSUE THREAD

**Issue by heshang91** [snake-lvyonghao/Tyut-Proxy#1]
我打算考研考太理的计算机专业的。

**Comment by snake-lvyonghao** [comment]
> 我打算考研考太理的计算机专业的。
哈哈哈哈，我是考研狗，请勿打扰，我是这个意思，你理解错了😄

**Comment by heshang91** [comment]
> > 我打算考研考太理的计算机专业的。
> > 哈哈哈哈，我是考研狗，请勿打扰，我是这个意思，你理解错了😄

好吧，那同学你考哪个带学啊？

**Comment by snake-lvyonghao** [comment]
> > > 我打算考研考太理的计算机专业的。
> 
> > > 哈哈哈哈，我是考研狗，请勿打扰，我是这个意思，你理解错了😄
> 
> 
> 
> 好吧，那同学你考哪个带学啊？

西电

**Comment by heshang91** [comment]
> > > > 我打算考研考太理的计算机专业的。
> > 
> > 
> > > > 哈哈哈哈，我是考研狗，请勿打扰，我是这个意思，你理解错了😄
> > 
> > 
> > 好吧，那同学你考哪个带学啊？
> 
> 西电

今年12月初试吗？

**Comment by snake-lvyonghao** [comment]
> > > > > 我打算考研考太理的计算机专业的。
> 
> > > 
> 
> > > 
> 
> > > > > 哈哈哈哈，我是考研狗，请勿打扰，我是这个意思，你理解错了😄
> 
> > > 
> 
> > > 
> 
> > > 好吧，那同学你考哪个带学啊？
> 
> > 
> 
> > 西电
> 
> 
> 
> 今年12月初试吗？

yes

**Comment by heshang91** [comment]
> > > > > > 我打算考研考太理的计算机专业的。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 哈哈哈哈，我是考研狗，请勿打扰，我是这个意思，你理解错了😄
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 好吧，那同学你考哪个带学啊？
> > 
> > 
> > > 
> > 
> > 
> > > 西电
> > 
> > 
> > 今年12月初试吗？
> 
> yes

太嗯了，祝你一战上岸嗷。

**Comment by snake-lvyonghao** [comment]
> > > > > > > 我打算考研考太理的计算机专业的。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 哈哈哈哈，我是考研狗，请勿打扰，我是这个意思，你理解错了😄
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 好吧，那同学你考哪个带学啊？
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 西电
> 
> > > 
> 
> > > 
> 
> > > 今年12月初试吗？
> 
> > 
> 
> > yes
> 
> 
> 
> 太嗯了，祝你一战上岸嗷。

谢谢谢谢，借你吉言
